language: ruby
rvm:
  - '2.4.2'
before_script:
  - cp -v config/database.yml.example config/database.yml
  - yarn install
  - ./bin/webpack
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec
