default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("WAHLGENIE_DB_NAME", "wahlgenie_#{Rails.env}") %>
  host: <%= ENV.fetch("WAHLGENIE_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("WAHLGENIE_DB_PORT", 5432) %>
  username: <%= ENV.fetch("WAHLGENIE_DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("WAHLGENIE_DB_PASSWORD", nil) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  # reconnect: false
  # socket: /tmp/postgres.sock
  timeout: 5000

development:
  <<: *default
  database: wahldatenhelfer_dev

test:
  <<: *default
  database: wahldatenhelfer_test

production:
  <<: *default
  database: wahldatenhelfer
