require('bootstrap')
require('fullpage.js')

// necessary for having those assets for rails application.
require('./images/wahl-daten-helfer-logo.svg')
require('./images/germany.svg')
require('./images/play-video.svg')
require('./images/play-video.svg')
require('./images/favicon.png')
require('./images/tatjana-lajendaecker.jpg')
require('./images/jan-kus.jpg')
require('./images/prototype-fund.svg')
require('./images/bmbf.svg')
require('./images/open-knowledge-foundation.svg')
require('./images/bksb.png')
