require('bootstrap')
require('fullpage.js')

// necessary for having those assets for rails application.
// require('./images/wahlgenial-logo.svg')
// require('./images/germany.svg')
// require('./images/play-video.svg')
// require('./images/play-video.svg')
// require('./images/favicon.png')
// require('./images/tatjana-lajendaecker.jpg')
// require('./images/jan-kus.jpg')
// require('./images/prototype-fund.svg')
// require('./images/bmbf.svg')
// require('./images/open-knowledge-foundation.svg')
// require('./images/bksb.png')
// require('./images/swoosh.svg')
// require('./images/badnews.jpg')
// require('./images/2559Direktkandidation.jpg')
// require('./images/deinWal.jpg')
// require('./images/sozialOMat.jpg')
// require('./images/logowahlen.jpg')
// require('./images/wahlswiper.jpg')
// require('./images/badnews.jpg')
// require('./images/badnews.jpg')
// require('./images/badnews.jpg')
// require('./images/badnews.jpg')
// require('./images/badnews.jpg')
// require('./images/badnews.jpg')

const importAll = r => r.keys().map(r)
importAll(require.context('./images/', true, /\.(png|jpe?g|svg|ico|svg|mp4)$/))
